# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{propaganda}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Rafter"]
  s.date = %q{2010-02-25}
  s.default_executable = %q{propaganda}
  s.description = %q{Propaganda uses Apache FOP to convert html to PDF using a series of stylesheets. Propaganda can also format textile and markdown documents. }
  s.email = %q{jeff@socialrange.org}
  s.executables = ["propaganda"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/propaganda",
     "java/SystemExitManager.class",
     "java/SystemExitManager.java",
     "java/avalon-framework-4.2.0.jar",
     "java/batik-all-1.7.jar",
     "java/commons-io-1.3.1.jar",
     "java/commons-logging-1.0.4.jar",
     "java/fop.jar",
     "java/org/apache/fop/cli/Manager$1.class",
     "java/org/apache/fop/cli/Manager.class",
     "java/org/apache/fop/cli/Manager.java",
     "java/serializer-2.7.0.jar",
     "java/xalan-2.7.0.jar",
     "java/xercesImpl-2.7.1.jar",
     "java/xml-apis-1.3.04.jar",
     "java/xml-apis-ext-1.3.04.jar",
     "java/xmlgraphics-commons-1.3.1.jar",
     "lib/propaganda.rb",
     "lib/propaganda/fop/bridge.rb",
     "lib/propaganda/fop/shell.rb",
     "lib/propaganda/formatter.rb",
     "lib/propaganda/renderer.rb",
     "templates/clean.xsl",
     "templates/default.xsl",
     "test/fop_test.rb",
     "test/helper.rb",
     "test/samples/sample.fo",
     "test/samples/sample.html",
     "test/samples/sample.markdown",
     "test/samples/sample.pdf",
     "test/samples/sample.textile"
  ]
  s.homepage = %q{http://github.com/jeffrafter/propaganda}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Generate PDFs from HTML. Generate them from Markdown and Textile. Take over the world.}
  s.test_files = [
    "test/fop_test.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<BlueCloth>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 4.1.1"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<BlueCloth>, [">= 1.0.0"])
      s.add_dependency(%q<RedCloth>, [">= 4.1.1"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<BlueCloth>, [">= 1.0.0"])
    s.add_dependency(%q<RedCloth>, [">= 4.1.1"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

